name: bump

on:
  schedule:
    - cron: "0 22 * * 1-5" # every weekday at 22:00 UTC
  workflow_dispatch:
    inputs:
      force:
        description: "Force bump"
        required: false
        type: choice
        default: "true"
        options:
          - "true"
          - "false"

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@a4440ed9daa3faedcfc8cd491dbcfa5e38d84156 # v1.8.14
        with:
          token: ${{ secrets.USER_TOKEN }}
          fetch_depth: 0

      - name: Bump
        uses: spotdemo4/bumper@32534ba92eb765a5dd0d22d2ee2064748d0a2042 # v0.2.5
        with:
          force: ${{ inputs.force }}
