name: check

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        id: init
        uses: spotdemo4/nix-init@050b8d7887f729841b2d104d745c642f2cf5c951 # v1.8.11

      - name: Run checks
        if: ${{ steps.init.outputs.duplicate != 'true' }}
        run: nix flake check
