name: release

on:
  push:
    tags: ["v*"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@63cc315d93acb3b914827e4ecd6c94d3358986f6 # v1.7.1

      - name: Run checks
        run: nix flake check

  release:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: https://gitea.com/actions/gitea-release-action@fe8e0322804b48e34e3bddbbf6335bd2b1046eb7 # v1

  linux-amd64:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@63cc315d93acb3b914827e4ecd6c94d3358986f6 # v1.7.1

      - name: Bundle
        run: nix bundle --bundler github:spotdemo4/nur#goToLinuxAmd64 -o template-linux-amd64

      - name: Release
        uses: https://gitea.com/actions/gitea-release-action@fe8e0322804b48e34e3bddbbf6335bd2b1046eb7 # v1
        with:
          files: template-linux-amd64

  linux-amd64-deb:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@63cc315d93acb3b914827e4ecd6c94d3358986f6 # v1.7.1

      - name: Bundle
        run: |
          nix bundle --bundler github:NixOS/bundlers#toDEB -o result
          cp result/*.deb template-linux-amd64.deb

      - name: Release
        uses: https://gitea.com/actions/gitea-release-action@fe8e0322804b48e34e3bddbbf6335bd2b1046eb7 # v1
        with:
          files: template-linux-amd64.deb

  linux-amd64-rpm:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@63cc315d93acb3b914827e4ecd6c94d3358986f6 # v1.7.1

      - name: Bundle
        run: |
          nix bundle --bundler github:NixOS/bundlers#toRPM -o result
          cp result/*.rpm template-linux-amd64.rpm

      - name: Release
        uses: https://gitea.com/actions/gitea-release-action@fe8e0322804b48e34e3bddbbf6335bd2b1046eb7 # v1
        with:
          files: template-linux-amd64.rpm

  linux-arm64:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@63cc315d93acb3b914827e4ecd6c94d3358986f6 # v1.7.1

      - name: Bundle
        run: nix bundle --bundler github:spotdemo4/nur#goToLinuxArm64 -o template-linux-arm64

      - name: Release
        uses: https://gitea.com/actions/gitea-release-action@fe8e0322804b48e34e3bddbbf6335bd2b1046eb7 # v1
        with:
          files: template-linux-arm64

  linux-arm:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@63cc315d93acb3b914827e4ecd6c94d3358986f6 # v1.7.1

      - name: Bundle
        run: nix bundle --bundler github:spotdemo4/nur#goToLinuxArm -o template-linux-arm

      - name: Release
        uses: https://gitea.com/actions/gitea-release-action@fe8e0322804b48e34e3bddbbf6335bd2b1046eb7 # v1
        with:
          files: template-linux-arm

  darwin-arm64:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@63cc315d93acb3b914827e4ecd6c94d3358986f6 # v1.7.1

      - name: Bundle
        run: nix bundle --bundler github:spotdemo4/nur#goToDarwinArm64 -o template-darwin-arm64

      - name: Release
        uses: https://gitea.com/actions/gitea-release-action@fe8e0322804b48e34e3bddbbf6335bd2b1046eb7 # v1
        with:
          files: template-darwin-arm64

  windows-amd64:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@63cc315d93acb3b914827e4ecd6c94d3358986f6 # v1.7.1

      - name: Bundle
        run: nix bundle --bundler github:spotdemo4/nur#goToWindowsAmd64 -o template-windows-amd64.exe

      - name: Release
        uses: https://gitea.com/actions/gitea-release-action@fe8e0322804b48e34e3bddbbf6335bd2b1046eb7 # v1
        with:
          files: template-windows-amd64

  container:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@63cc315d93acb3b914827e4ecd6c94d3358986f6 # v1.7.1

      - name: Bundle
        run: nix bundle --bundler github:spotdemo4/nur#toDockerStream -o result

      - name: Release
        run: |
          mkdir -p /etc/containers
          curl -L -o /etc/containers/policy.json https://raw.githubusercontent.com/containers/image/main/default-policy.json

          ./result \
          | gzip --fast \
          | nix shell nixpkgs#skopeo \
            --inputs-from . \
            --command skopeo copy \
            --dest-creds=${{ github.actor }}:${{ secrets.USER_TOKEN }} \
            docker-archive:/dev/stdin \
            docker${GITHUB_SERVER_URL#https}/${GITHUB_REPOSITORY@L}:${GITHUB_REF_NAME#v}
