name: update

on:
  schedule:
    - cron: "0 9 * * *" # every day at 09:00 UTC
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@531af3ea9560d03f371c7c27d71d3b73c1165249 # v1.8.6
        with:
          shell: update

      - name: Renovate
        env:
          RENOVATE_CONFIG_FILE: .gitea/renovate.json
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_GITHUB_COM_TOKEN: ${{ secrets.GH_TOKEN }}
        run: renovate
