name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: release

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@757d5ba1fa0749e877484703bece0e17c7bd5670 # v1.43.0
        with:
          fetch_depth: 0
          shell: release

      - name: Release to GitHub
        run: flake-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY: ghcr.io
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          PACKAGES: |
            appimages.x86_64-linux.default.aarch64-unknown-linux-gnu
            appimages.x86_64-linux.default.armv7l-unknown-linux-gnueabihf
            appimages.x86_64-linux.default.x86_64-unknown-linux-gnu
            images.x86_64-linux.default.aarch64-unknown-linux-gnu
            images.x86_64-linux.default.armv7l-unknown-linux-gnueabihf
            images.x86_64-linux.default.x86_64-unknown-linux-gnu

      - name: Release to NPM
        run: npm publish --access public

      - name: Publish to FlakeHub
        uses: DeterminateSystems/flakehub-push@71f57208810a5d299fc6545350981de98fdbc860 # v6
        with:
          visibility: public
